### ISSUE TITLE
react-native and "SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0)"

### ISSUE THREAD

**Issue by adamski** [babel/babylon#287]
I am getting the above error from babylon when running a react-native app in the simulator (debug mode). 

```
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
    at Parser.pp$5.raise (/path-to/node_modules/babylon/lib/index.js:4246:13)
    at Parser.pp$1.parseStatement (/path-to/node_modules/babylon/lib/index.js:1749:16)
    at Parser.pp$1.parseBlockBody (/path-to/node_modules/babylon/lib/index.js:2133:21)
    at Parser.pp$1.parseTopLevel (/path-to/node_modules/babylon/lib/index.js:1645:8)
    at Parser.parse (/path-to/node_modules/babylon/lib/index.js:1537:17)
    at Object.parse$1 [as parse] (/path-to/node_modules/babylon/lib/index.js:6466:37)
    at extractDependencies (/path-to/node_modules/react-native/packager/react-packager/src/JSTransformer/worker/extract-dependencies.js:29:23)
    at transform (/path-to/node_modules/react-native/packager/react-packager/src/JSTransformer/worker/index.js:53:9)
    at module.exports (/path-to/node_modules/react-native/packager/transformer.js:130:3)
    at transformCode (/path-to/node_modules/react-native/packager/react-packager/src/JSTransformer/worker/index.js:27:3)
transformed 35/139 (25%)/path-to/node_modules/babylon/lib/index.js:4249
  throw err;
```

I'm currently using the `babel-preset-react-native-stage-0` package, in order to use decorators with MobX. 

### Babylon/Babel Configuration

my package.json:
```js
  "dependencies": {
    "apsl-react-native-button": "^3.0.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "mobx": "^2.7.0",
    "mobx-react": "^3.5.5",
    "react": "15.3.2",
    "react-native": "0.38.0",
    "react-native-autogrow-textinput": "^2.0.3",
    "react-native-awesome-button": "^1.6.0",
    "react-native-couchbase-lite": "git://github.com/adamski/react-native-couchbase-lite.git#gradle-experimental",
    "react-native-keep-awake": "git://github.com/adamski/react-native-keep-awake.git#experimental-gradle",
    "react-native-keyboard-aware-view": "^0.0.11",
    "react-native-keyboard-dodging-view": "git://github.com/adamski/react-native-keyboard-dodging-view#upper-text-inputs",
    "react-native-modalbox": "^1.3.4",
    "react-native-navigation": "git://github.com/adamski/react-native-navigation.git#gradle-experimental-update",
    "react-native-searchbar": "^0.4.2",
    "react-native-simple-store": "^1.0.1",
    "react-native-swipe-list-view": "^0.3.1"
  },
```

and my `.babelrc`:

```js
{
  "presets": ["react-native", "react-native-stage-0/decorator-support"]
}
```

### Expected Behaviour
No error message, debug builds 

### Current Behaviour
Error message comes up on `npm start` and app fails to load

### Your Environment
| software         | version
| ---------------- | -------
| Babylon          |  6.11 - 6.14
| node             |  6.8.0
| npm              |  3.10.8
| yarn              | 0.17.9
| Operating System | OSX 10.11

Also `ag babylon` yields
```
yarn.lock
200:    babylon "^6.11.0"
885:    babylon "^6.11.0"
896:    babylon "^6.11.0"
911:babylon@^6.11.0, babylon@^6.13.0, babylon@^6.13.1:
913:  resolved "https://registry.yarnpkg.com/babylon/-/babylon-6.14.1.tgz#956275fab72753ad9b3435d7afe58f8bf0a29815"
3478:    babylon "^6.13.0"
3555:    babylon "^6.13.1"
``` 
which suggests a conflict among different versions of babylon?

I asked the question on SO a few days ago: http://stackoverflow.com/questions/41424631/syntaxerror-import-and-export-may-appear-only-with-sourcetype-module-1/41472361#41472361 (and also put a bounty on it!)

**Comment by danez** [comment]
Please ask in the react-native tracker or maybe you already fixed it by now. But we cannot help you here as we do not know how babylon is used and which package is using it.

**Comment by stevenyap** [comment]
To those who may have found this post, I solved this problem by changing my .babelrc to
```
{
  "presets": ["babel-preset-react-native"]
}
```
