### ISSUE TITLE
Parsing of class properties [help]

### ISSUE THREAD

**Issue by yuri1992** [babel/babylon#385]
### Input Code

```js
class Form extends React.Component {

    static propTypes = {
        onFinish: React.PropTypes.func,
        notifyUser: React.PropTypes.func,
        canSubmit: React.PropTypes.func,
        onSubmit: React.PropTypes.func,
        paymentMethod: React.PropTypes.object
    };
```

### Babylon/Babel Configuration

```js
{
  "presets": [
    "es2015",
    "react"
  ],
  "plugins": [
    "transform-class-properties"
  ]
}

```

### Expected Behavior

parsing static class properties

### Current Behavior

```bash
/home/yurir/Development/sef-new/node_modules/babel-jsxgettext/node_modules/babylon/lib/index.js:4376
  throw err;
  ^

SyntaxError: Unexpected token (11:21)
    at Parser.pp$5.raise (/home/yurir/Development/sef-new/node_modules/babel-jsxgettext/node_modules/babylon/lib/index.js:4373:13)
    at Parser.pp.unexpected (/home/yurir/Development/sef-new/node_modules/babel-jsxgettext/node_modules/babylon/lib/index.js:1716:8)
    at Parser.pp$1.parseClassProperty (/home/yurir/Development/sef-new/node_modules/babel-jsxgettext/node_modules/babylon/lib/index.js:2507:50)
    at Parser.pp$1.parseClassBody (/home/yurir/Development/sef-new/node_modules/babel-jsxgettext/node_modules/babylon/lib/index.js:2424:34)
    at Parser.pp$1.parseClass (/home/yurir/Development/sef-new/node_modules/babel-jsxgettext/node_modules/babylon/lib/index.js:2361:8)
    at Parser.pp$1.parseStatement (/home/yurir/Development/sef-new/node_modules/babel-jsxgettext/node_modules/babylon/lib/index.js:1798:19)
    at Parser.pp$1.parseBlockBody (/home/yurir/Development/sef-new/node_modules/babel-jsxgettext/node_modules/babylon/lib/index.js:2223:21)
    at Parser.pp$1.parseTopLevel (/home/yurir/Development/sef-new/node_modules/babel-jsxgettext/node_modules/babylon/lib/index.js:1733:8)
    at Parser.parse (/home/yurir/Development/sef-new/node_modules/babel-jsxgettext/node_modules/babylon/lib/index.js:1628:17)
    at Object.parse (/home/yurir/Development/sef-new/node_modules/babel-jsxgettext/node_modules/babylon/lib/index.js:7083:37)
```

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  6.16.1
| node             |  v7.2.1
| npm              | npm@3.10.10
| Operating System | archlinux

**Comment by loganfsmyth** [comment]
Given that the error is from inside `babel-jsxgettext`, if I had to guess, that module does not take into account Babel plugins and such. You'd have to see if it exposes a way to handle class properties and such.
