### ISSUE TITLE
`make test-babel` fails on master

### ISSUE THREAD

**Issue by andy-ms** [babel/babylon#453]
I get these errors:

```ts
  1) babel-plugin-transform-async-to-generator/async to generator shadowed promise:

      /home/andy/bab/babylon/build/babel/packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/shadowed-promise/actual.js !== /home/andy/bab/babylon/build/babel/packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/shadowed-promise/expected.js
      + expected - actual

           return _ref.apply(this, arguments);
         };
       })();
       
      -function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { Promise.resolve(value).then(_next, _throw); } } function _next(value) { step("next", value); } function _throw(err) { step("throw", err); } _next(); }); }; }
      +function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { return Promise.resolve(value).then(function (value) { step("next", value); }, function (err) { step("throw", err); }); } } return step("next"); }); }; }
       
       let _Promise;
      
      at run (packages/babel-helper-transform-fixture-test-runner/lib/index.js:295:47)
      at runTask (packages/babel-helper-transform-fixture-test-runner/lib/index.js:25:13)
      at Context.<anonymous> (packages/babel-helper-transform-fixture-test-runner/lib/index.js:55:15)

  2) babel-plugin-transform-async-to-generator/async to generator shadowed promise import:

      /home/andy/bab/babylon/build/babel/packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/shadowed-promise-import/actual.js !== /home/andy/bab/babylon/build/babel/packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/shadowed-promise-import/expected.js
      + expected - actual

           return _ref.apply(this, arguments);
         };
       })();
       
      -function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { Promise.resolve(value).then(_next, _throw); } } function _next(value) { step("next", value); } function _throw(err) { step("throw", err); } _next(); }); }; }
      +function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { return Promise.resolve(value).then(function (value) { step("next", value); }, function (err) { step("throw", err); }); } } return step("next"); }); }; }
       
       import _Promise from 'somewhere';
      
      at run (packages/babel-helper-transform-fixture-test-runner/lib/index.js:295:47)
      at runTask (packages/babel-helper-transform-fixture-test-runner/lib/index.js:25:13)
      at Context.<anonymous> (packages/babel-helper-transform-fixture-test-runner/lib/index.js:55:15)

  3) babel-plugin-transform-async-to-generator/async to generator shadowed promise nested:

      /home/andy/bab/babylon/build/babel/packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/shadowed-promise-nested/actual.js !== /home/andy/bab/babylon/build/babel/packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/shadowed-promise-nested/expected.js
      + expected - actual

           return _ref.apply(this, arguments);
         };
       })();
       
      -function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { Promise.resolve(value).then(_next, _throw); } } function _next(value) { step("next", value); } function _throw(err) { step("throw", err); } _next(); }); }; }
      +function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { return Promise.resolve(value).then(function (value) { step("next", value); }, function (err) { step("throw", err); }); } } return step("next"); }); }; }
       
       let _Promise;
      
      at run (packages/babel-helper-transform-fixture-test-runner/lib/index.js:295:47)
      at runTask (packages/babel-helper-transform-fixture-test-runner/lib/index.js:25:13)
      at Context.<anonymous> (packages/babel-helper-transform-fixture-test-runner/lib/index.js:55:15)
```

Had to run `npm install -g async commander colors rimraf winston` and `sudo apt install jq` first. Running on node 7.8.0 on Linux Mint 18.

**Comment by hzoo** [comment]
Hey @andy-ms! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by hzoo** [comment]
Oh I just merged https://github.com/babel/babel/pull/5548

Btw are you in our slack? can have an easier time with this stuff there

**Comment by hzoo** [comment]
Looks like just need to fix the tests since old pr didn't update the other tests, fixing now

**Comment by andy-ms** [comment]
Yeah, I'm on slack.

**Comment by hzoo** [comment]
https://github.com/babel/babel/commit/2a874dff8cb0b96228e645a2e2fa4dbb818ebfd3
