### ISSUE TITLE
Linking with babel causes TypeError

### ISSUE THREAD

**Issue by andy-ms** [babel/babylon#534]
Following the instructions from `CONTRIBUTING.md`:

```sh
cd babylon
git checkout master
yarn link
yarn run build

cd ../babel
git checkout master
make bootstrap
yarn link babylon
cd packages/babel-core/
yarn link babylon
cd ../babel-template/
yarn link babylon
cd ../babel-traverse/
yarn link babylon
cd ../babel-generator/
yarn link babylon
cd ../babel-types/
yarn link babylon
cd ../..
make build
```

Causes this error:

```
TypeError: /home/andy/bbl/babel/packages/babel-core/src/transformation/file/options/option-manager.js: Property property of MemberExpression expected node to be of a type ["Identifier"] but instead got null
    at validate (/home/andy/bbl/babel/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/home/andy/bbl/babel/node_modules/babel-types/lib/definitions/core.js:412:50)
    at validate (/home/andy/bbl/babel/node_modules/babel-types/lib/index.js:505:9)
    at Object.builder (/home/andy/bbl/babel/node_modules/babel-types/lib/index.js:466:7)
    at DestructuringTransformer.pushObjectProperty (/home/andy/bbl/babel/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:174:22)
    at DestructuringTransformer.pushObjectPattern (/home/andy/bbl/babel/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:200:16)
    at DestructuringTransformer.push (/home/andy/bbl/babel/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:108:14)
    at DestructuringTransformer.init (/home/andy/bbl/babel/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:317:12)
    at PluginPass.VariableDeclaration (/home/andy/bbl/babel/node_modules/babel-plugin-transform-es2015-destructuring/lib/index.js:468:27)
    at newFn (/home/andy/bbl/babel/node_modules/babel-traverse/lib/visitors.js:276:21)
```

### Your Environment

| software         | version
| ---------------- | -------
| node             | 7.10.0
| npm              | 4.2.0
| Operating System | Linux Mint 18

**Comment by hzoo** [comment]
Hey @andy-ms! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.

**Comment by andy-ms** [comment]
Never mind, had checked out `master` on babel when I should have used `7.0`.
