### ISSUE TITLE
TypeScript plugin produces different error for invalid JSX

### ISSUE THREAD

**Issue by JamesHenry** [babel/babylon#674]
Pretty random issue found when performing AST comparison tests in `typescript-eslint-parser`.

Normally the source below should produce a `SyntaxError`, and indeed it usually does in babylon. However, when the `typescript` plugin is enabled, it produces a `RangeError`.

### Input Code

```js
</>;
```

### Babylon/Babel Configuration

Using Babylon `7.0.0-beta.19`

```js
function parseWithBabylonPluginTypescript(text) {
    const babylon = require("babylon");
    return babylon.parse(text, {
        sourceType: "script",
        allowImportExportEverywhere: true,
        allowReturnOutsideFunction: true,
        ranges: true,
        plugins: [
            "jsx",
            // "typescript", // <- If this is commented out, SyntaxError, if not RangeError
            "doExpressions",
            "objectRestSpread",
            "decorators",
            "classProperties",
            "exportExtensions",
            "asyncGenerators",
            "functionBind",
            "functionSent",
            "dynamicImport",
            "numericSeparator",
            "estree"
        ]
    });
}
```

### Expected Behavior
SyntaxError thrown

### Current Behavior
RangeError thrown

### Stack trace for RangeError case (i.e. with typescript plugin enabled)

```
RangeError: Invalid array length
    at _class.updateContext (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:7896:35)
    at _class.finishToken (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:1150:10)
    at _class.finishOp (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:1466:17)
    at _class.readToken_slash (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:1192:19)
    at _class.getTokenFromCode (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:1424:21)
    at _class.readToken (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:1027:19)
    at _class.readToken (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:7879:46)
    at _class.readToken (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:9725:48)
    at _class.nextToken (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:1015:19)
    at _class.next (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:947:10)
    at _class.parseMaybeAssign (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:9555:12)
    at _class.parseExpression (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:2564:21)
    at _class.parseStatementContent (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:3993:21)
    at _class.parseStatementContent (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:9275:58)
    at _class.parseStatement (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:3881:17)
    at _class.parseBlockOrModuleBlockBody (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:4426:23)
    at _class.parseBlockBody (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:4412:10)
    at _class.parseBlockBody (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:5438:44)
    at _class.parseTopLevel (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:3849:10)
    at _class.parse (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:5265:17)
    at Object.parse (/Users/james/Documents/typescript-eslint-parser/node_modules/babylon/lib/index.js:9775:36)
    at parseWithBabylonPluginTypescript (/Users/james/Documents/typescript-eslint-parser/tests/ast-alignment/parse.js:18:20)```

**Comment by hzoo** [comment]
Hey @JamesHenry! We really appreciate you taking the time to report an issue. The collaborators
on this project attempt to help as many people as possible, but we're a limited number of volunteers,
so it's possible this won't be addressed swiftly.

If you need any help, or just have general Babel or JavaScript questions, we have a vibrant Slack
community that typically always has someone willing to help. You can sign-up [here](https://slack.babeljs.io/)
for an invite.
